### ISSUE TITLE
When adding a new page, I want to build the layout without distractions

### ISSUE THREAD

**Issue by perandre** [front/storypage#1]
Currently after adding a page, I feel that I'm about to write an article. What I want is an easy to use UI to create a news front page.

1. It says: Write your story. Perhaps change to: "Add content"
2. If I click + to add a row, the sidebar displays Paragraph block, which invites me to start typing. Default to Dynamic row instead? Or, is it possible to just have the page blank?
3. Perhaps rename Rows Blocks to "StoryPage columns"

**Comment by SofiaSousa** [comment]
@perandre changes are available now ([0.1.0](https://github.com/front/storypage/tree/0.1.0)).

Could you please test it and give some feedback about the user experience before closing this issue?

**Comment by perandre** [comment]
Hi, thanks for the fixes. 2) seems to not work, still? After adding a Row, keep focus on the Row (not the paragraph inside), so I can make row settings in sidebar.

As I'm testing however, I find that I am still not satisfied with the UX. Some thoughts:

- We don't need both Section block; it sound the same as Row, and a user wouldn't know which of the two to use. 
- Adding a new Row should probably a edge feature; I'm thinking now that Pre-designed (populated) sections should be the go-to way to build a page. 

Btw: I get a lot of this error, making it a bit hard to test:

![error](https://user-images.githubusercontent.com/118979/42019742-379db8a2-7ab6-11e8-9471-11b96f149072.png)

Anyways: After fixing 2) I'll close this, and focus can be shifted to Pre-designed sections, which gives us a much easier way to build pages.

**Comment by SofiaSousa** [comment]
About the error, could you clear the browser local storage and check if it happens again?

Row and Section block are different: 

- Row is slipt in 2 or more columns and the user can define the width of each one.
- Section can be seen as a row with just one column, ok. But it isn't dynamic (the user can't add/remove columns) and is used to wrap blocks and give them the same background, for example.

Technically, they could be the same block, but I think what they represent is different: section is a slot; row it's a bundle of slots.
